apiVersion: v1
kind: Pod
metadata:
  name: flask-docker
  namespace: pankaj-singh
  labels:
    app: web
    env: dev
    role: fe
spec:
  containers:
  - name: flask-docker
    image: pankajkrsingh/flask_docker:latest
    ports:
    - containerPort: 80
